// source/frontend/components/web-components/Footer.tsx
import React from 'react';


export default function Footer() {
    return (
        <footer className="pt-32 pb-10 bg-[#202024] mb:pl-5 mb:pr-5">
            <div className="text-center text-4xl text-white pt-3 pb-20">
                Derailed, the free gaming platform for chat.
            </div>
            <div className="flex justify-center items-center pt-7 text-sm" style={{gap: 15}}>
                <a href="/about" className="text-center text-[#737f8d]">About</a>
                <a href="https://blog.derailed.one" className="text-center text-[#737f8d]">Blog</a>
                <a href="/terms" className="text-center text-[#737f8d]">Terms of Service</a>
                <a href="/privacy" className="text-center text-[#737f8d]">Privacy Policy</a>
            </div>
	    </footer>
    )
}

// website/src/lib/components/footer.svelte
<script lang="ts">
	import bob from '$lib/assets/bob.png';
</script>

<footer
	class="text-[#e8e8ed] pb-24 font-main"
	style="font-variation-settings: 'ital' 0, 'wdth' 125;"
>
	<div class="flex justify-center">
		<img alt="Bob" src={bob} class="w-7 mb-14 sm:block lg:hidden" />
	</div>
	<div class="flex flex-wrap justify-center items-center gap-40">
		<img alt="Bob" src={bob} class="w-7 mb-14 sm:hidden lg:block" />
		<div id="home">
			<h1 class="font-semibold mb-3.5 text-white">Home</h1>
			<a href="/">
				<h3 class="hover:text-white">Home</h3>
			</a>
			<a href="/features">
				<h3 class="hover:text-white">Features</h3>
			</a>
			<a href="https://blog.derailed.one">
				<h3 class="hover:text-white">Blog</h3>
			</a>
		</div>

		<div id="resources" class="mb-5">
			<h1 class="font-semibold mb-3.5 text-white">Resources</h1>
			<a href="/terms">
				<h3 class="hover:text-white">Terms</h3>
			</a>
			<a href="/privacy">
				<h3 class="hover:text-white">Privacy Policy</h3>
			</a>
		</div>
	</div>
</footer>
